/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WishlistImport } from './routes/wishlist'
import { Route as IndexImport } from './routes/index'
import { Route as ProductsDetailsImport } from './routes/products.$details'
import { Route as CategoryCategoryImport } from './routes/category.$category'

// Create/Update Routes

const WishlistRoute = WishlistImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProductsDetailsRoute = ProductsDetailsImport.update({
  id: '/products/$details',
  path: '/products/$details',
  getParentRoute: () => rootRoute,
} as any)

const CategoryCategoryRoute = CategoryCategoryImport.update({
  id: '/category/$category',
  path: '/category/$category',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistImport
      parentRoute: typeof rootRoute
    }
    '/category/$category': {
      id: '/category/$category'
      path: '/category/$category'
      fullPath: '/category/$category'
      preLoaderRoute: typeof CategoryCategoryImport
      parentRoute: typeof rootRoute
    }
    '/products/$details': {
      id: '/products/$details'
      path: '/products/$details'
      fullPath: '/products/$details'
      preLoaderRoute: typeof ProductsDetailsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/wishlist': typeof WishlistRoute
  '/category/$category': typeof CategoryCategoryRoute
  '/products/$details': typeof ProductsDetailsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/wishlist': typeof WishlistRoute
  '/category/$category': typeof CategoryCategoryRoute
  '/products/$details': typeof ProductsDetailsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/wishlist': typeof WishlistRoute
  '/category/$category': typeof CategoryCategoryRoute
  '/products/$details': typeof ProductsDetailsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/wishlist' | '/category/$category' | '/products/$details'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/wishlist' | '/category/$category' | '/products/$details'
  id:
    | '__root__'
    | '/'
    | '/wishlist'
    | '/category/$category'
    | '/products/$details'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WishlistRoute: typeof WishlistRoute
  CategoryCategoryRoute: typeof CategoryCategoryRoute
  ProductsDetailsRoute: typeof ProductsDetailsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WishlistRoute: WishlistRoute,
  CategoryCategoryRoute: CategoryCategoryRoute,
  ProductsDetailsRoute: ProductsDetailsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/wishlist",
        "/category/$category",
        "/products/$details"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/wishlist": {
      "filePath": "wishlist.ts"
    },
    "/category/$category": {
      "filePath": "category.$category.ts"
    },
    "/products/$details": {
      "filePath": "products.$details.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
