export const items = [
	{
		productId: 1, 
		name: 'Ofada Rice1', 
		weight: { value: 2, measurement: 'kg' }, 
		isWishListItem: false,
		category: 'flour',
		price: 22, 
		productDetails: `Discover the rich, authentic flavor of traditional pounded yam with Kobobasket Poundo Yam Flour. Perfect for busy families and food lovers, this premium flour ensures quick and easy preparation while delivering unmatched taste and quality.`,
		productDescription: 'Lorem ipsum dolor sit amet consectetur. Commodo morbi diam mauris nibh nibh vitae vestibulum pellentesque euismod. Curabitur pellentesque consequat elementum blandit euismod. Placerat faucibus dignissim porta sodales.',
		locationPrice: 35, 
		images: ["", "", ''], 
	},
	{
		productId: 2, 
		name: 'Smoked Panla Fish', 
		weight: { value: 3, measurement: 'kg' }, 
		price: 15, 
		isWishListItem: false,
		category: '',
		locationPrice: 30, 
		images: [""], 
		promotion: { 
			promoName: "Valentine's Deals", 
			promoPrice: 10 
		}
	},
	{
		productId: 24, 
		name: 'Ijebu Garri', 
		weight: { value: 3, measurement: 'kg' }, 
		price: 15, 
		isWishListItem: false,
		category: '',
		locationPrice: 30, 
		images: [""], 
		
	},
	{
		productId: 5, 
		name: 'Dried Ugwu Leaf', 
		weight: { value: 3, measurement: 'kg' },
		price: 15, 
		isWishListItem: false,
		category: '',
		locationPrice: 20, 
		images: [""], 
	},
	{
		productId: 3, 
		name: 'Cameroon Pepper',  
		weight: { value: 500, measurement: 'g' },
		isWishListItem: false,
		category: '',
		price: 29, 
		locationPrice: 35, 
		images: [""], 
		promotion: { 
			promoName: 'Kobo Specials', 
			promoPrice: 10 
		}
	},
	{
		productId: 6, 
		name: 'Periwinkle', 
		weight: { value: 500, measurement: 'g' },
		isWishListItem: true,
		category: '',
		price: 29, 
		locationPrice: 35, 
		images: [""], 
	},
	{
		productId: 7, 
		name: 'Locust Beans (Iru)', 
		weight: { value: 800, measurement: 'g' },
		isWishListItem: false,
		category: '',
		price: 24, 
		locationPrice: 30, 
		images: [""], 
	},
	{
		productId: 9, 
		name: 'Orijin Bitter', 
		weight: { value: 0.1, measurement: 'kg' },
		isWishListItem: false,
		category: '',
		price: 9, 
		locationPrice: 15, 
		images: [""], 
		promotion: { 
			promoName: 'Kobo Specials', 
			promoPrice: 7 
		}
	},
	{
		productId: 10, 
		name: 'Yellow Garri', 
		weight: { value: 1, measurement: 'kg' },
		isWishListItem: false,
		category: '',
		price: 24, 
		locationPrice: 30, 
		images: [""], 
	},
	{
		productId: 11, 
		name: 'Beans Flour',
		weight: { value: 700, measurement: 'g' },
		isWishListItem: false,
		category: '',
		price: 22, 
		locationPrice: 28, 
		images: [""], 
	},
	{
		productId: 12, 
		name: 'Palm Oil', 
		weight: { value: 5, measurement: 'kg' },
		isWishListItem: false,
		category: '',
		price: 26, 
		locationPrice: 30, 
		images: [""], 
		promotion: { 
			promoName: 'Black friday', 
			promoPrice: 20 
		}
	},
	{
		productId: 13, 
		name: 'Local Spice', 
		weight: { value: 2, measurement: 'kg' },
		isWishListItem: false,
		category: '',
		price: 15, 
		locationPrice: 24, 
		images: [""], 
	},
	{
		productId: 14, 
		name: 'Water Leaf', 
		weight: { value: 500, measurement: 'g' },
		isWishListItem: false,
		category: '',
		price: 24, 
		locationPrice: 32, 
		images: [""], 
	},
	{
		productId: 15, 
		name: 'Cray Fish', 
		weight: { value: 5, measurement: 'kg' },
		isWishListItem: false,
		category: '',
		price: 30, 
		locationPrice: 35, 
		images: [""], 
		promotion: { 
			promoName: 'Kobo Specials', 
			promoPrice: 25 
		}
	},
	{
		productId: 16, 
		name: 'Kilishi', 
		weight: { value: 500, measurement: 'g' },
		isWishListItem: false,
		category: '',
		price: 20, 
		locationPrice: 28, 
		images: [""], 
	}
]; 